"""
table_regime_fr_buffer.py
--------------------------
Table 4.5.2 — FR outcomes by VSTOXX regime (run_042 out-of-sample)
Table 4.5.3 — Buffer flows by VSTOXX regime (run_042 out-of-sample)

Three-way comparison: DRL (PPO) | Fixed-Rule ALM | Hoevenaars ALM (v4).

Metrics per regime:
  Table 4.5.2: mean monthly DeltaFR, annualised FR return, FR MDD within regime, Calmar
  Table 4.5.3: mean fill rate f_tilde, mean distribution rate d_tilde

Calmar per regime = (mean DeltaFR * 12) / abs(max_drawdown of FR within regime).
Max drawdown computed over the ordered FR values at regime timesteps.

Hoevenaars trajectory is generated by re-running the v4 headline agent
(loaded from results/hoevenaars_v4_headline_policy.json) on the actual
Jan 2018 – Dec 2025 test path via the same WtpPensionEnv used by DRL and
Fixed-Rule.  mu_vstoxx (67th-pct training VSTOXX) is re-derived from the
training feature matrix so there is no external dependency on a calibration
JSON that may have been produced by an earlier code version.
"""

import json
import sys
sys.path.insert(0, ".")

import numpy as np
import pandas as pd

from src.data_pipeline import run_pipeline
from src.environment   import EnvConfig, make_env_from_pipeline
from src.baselines      import run_episode
from src.hoevenaars_alm import HoevenaarsALM

# ── Load DRL and Fixed-Rule trajectories ─────────────────────────────────────
drl = np.load("src/models/run_042/trajectory_drl_ppo.npz")
fxd = np.load("src/models/run_042/trajectory_fixed-rule.npz")

dates = pd.to_datetime(drl["dates"])
T     = len(dates)

# ── Load market data (VSTOXX for regime classification) ──────────────────────
results = run_pipeline()
cfg     = EnvConfig()
z_raw   = results["z_test_raw"]

vstoxx_all = z_raw["vstoxx_level"].values
idx_start  = cfg.lookback - 1          # 11: first full lookback window
vstoxx_t   = vstoxx_all[idx_start : idx_start + T]

# ── Derive mu_vstoxx from training data (67th percentile) ────────────────────
# The v4 Hoevenaars policy de-risks equity only when VSTOXX exceeds this
# threshold.  It must match the value used during Bayesian optimisation.
z_train_raw = results["z_train_raw"]
mu_vstoxx   = float(np.percentile(z_train_raw["vstoxx_level"].values, 67))
print(f"  mu_vstoxx (67th-pct training VSTOXX) = {mu_vstoxx:.4f}")

# ── Run Hoevenaars v4 agent on the historical test path ───────────────────────
# Load the pre-committed headline parameters selected via Pareto-front rule.
with open("results/hoevenaars_v4_headline_policy.json") as fh:
    hl = json.load(fh)
p  = hl["params"]
hoev_params = np.array([
    p["a"], p["h"], p["i"], p["c"], p["g"], p["e"], p["B_target"], p["B_min"]
], dtype=np.float64)

# Raw (unscaled) VSTOXX for the test split — needed by the v4 predict() call
# because the obs vector contains scaled features and the v4 tilt formula
# requires the actual VSTOXX level compared against mu_vstoxx.
vstoxx_test_raw = results["z_test"]["vstoxx_level"].values  # (T_test,) unscaled

hoev_agent = HoevenaarsALM(
    params        = hoev_params,
    mu_vstoxx     = mu_vstoxx,
    vstoxx_series = vstoxx_test_raw,
)

env_hoev  = make_env_from_pipeline(results, split="test", cfg=cfg, seed=0)
traj_hoev = run_episode(hoev_agent, env_hoev)

# Build numpy arrays aligned to the same T steps as DRL/Fixed-Rule
hoev_FR      = np.array(traj_hoev["FR"])
hoev_f_tilde = np.array(traj_hoev["f_tilde"])
hoev_d_tilde = np.array(traj_hoev["d_tilde"])

# Sanity check: terminal FR should match hoevenaars_v4_historical.csv (1.489)
print(f"  Hoevenaars FR terminal = {hoev_FR[-1]:.4f}  (expected ~1.4895)")

# ── Helpers ───────────────────────────────────────────────────────────────────

def max_drawdown(fr: np.ndarray) -> float:
    """Max peak-to-trough drawdown of a FR series."""
    if len(fr) < 2:
        return 0.0
    peak = fr[0]
    mdd  = 0.0
    for v in fr[1:]:
        if v > peak:
            peak = v
        dd = peak - v
        if dd > mdd:
            mdd = dd
    return float(mdd)


def calmar(fr: np.ndarray) -> float:
    """Annualised mean monthly DeltaFR / abs(MDD). NaN if MDD=0."""
    if len(fr) < 2:
        return float("nan")
    delta_fr = np.diff(fr)
    ann_ret  = delta_fr.mean() * 12
    mdd      = max_drawdown(fr)
    if mdd < 1e-8:
        return float("nan")
    return ann_ret / mdd


# ── Regime masks ──────────────────────────────────────────────────────────────
regimes = [
    ("Low",    "<20",    vstoxx_t <  20),
    ("Medium", "20-30",  (vstoxx_t >= 20) & (vstoxx_t < 30)),
    ("High",   ">=30",   vstoxx_t >= 30),
    ("Overall","all",    np.ones(T, dtype=bool)),
]

# ── Compute per-regime FR metrics ─────────────────────────────────────────────
def fr_metrics(fr: np.ndarray, mask: np.ndarray) -> dict:
    # Correct approach: compute month-by-month deltas first, then select regime
    # months.  np.diff(fr[mask]) is WRONG for non-contiguous masks because it
    # computes differences between non-adjacent calendar months.
    delta_fr_all = np.diff(fr)          # (T-1,) true monthly changes
    mask_d = mask[1:]                   # change at t uses mask[t]
    delta_fr = delta_fr_all[mask_d]
    if len(delta_fr) == 0:
        return {"delta_fr_mo": float("nan"), "ann_ret": float("nan"),
                "mdd": float("nan"), "calmar": float("nan")}
    ann_ret  = delta_fr.mean() * 12
    fr_m = fr[mask]
    mdd  = max_drawdown(fr_m)
    cal  = ann_ret / mdd if mdd > 1e-8 else float("nan")
    return {
        "delta_fr_mo": float(delta_fr.mean()),
        "ann_ret":     float(ann_ret),
        "mdd":         float(mdd),
        "calmar":      float(cal),
    }

# ── Compute per-regime buffer flow metrics ────────────────────────────────────
def buffer_metrics(f_tilde: np.ndarray, d_tilde: np.ndarray,
                   mask: np.ndarray) -> dict:
    return {
        "fill_mean": float(f_tilde[mask].mean()),
        "dist_mean": float(d_tilde[mask].mean()),
    }

# ─────────────────────────────────────────────────────────────────────────────
# TABLE 4.5.2 — FR outcomes by regime
# ─────────────────────────────────────────────────────────────────────────────
print("=" * 110)
print("Table 4.5.2 -- FR Outcomes by VSTOXX Regime  (run_042, T=85 months)")
print("=" * 110)
hdr = (f"{'Regime':<12} {'VSTOXX':>8} {'n':>4}"
       f" {'DRL DFR/mo':>11} {'FR DFR/mo':>10} {'Hoev DFR/mo':>12}"
       f" {'DRL Ann%':>10} {'FR Ann%':>9} {'Hoev Ann%':>11}")
print(hdr)
print("-" * 110)

for label, band, mask in regimes:
    n   = int(mask.sum())
    dm  = fr_metrics(drl["FR"], mask)
    fm  = fr_metrics(fxd["FR"], mask)
    hm  = fr_metrics(hoev_FR, mask)

    def _fmt(v):
        return f"{v:+.4f}" if not np.isnan(v) else "   n/a"
    def _fmt_pct(v):
        return f"{v*100:+.1f}%" if not np.isnan(v) else "  n/a"

    print(f"{label:<12} {band:>8} {n:>4}"
          f" {_fmt(dm['delta_fr_mo']):>11} {_fmt(fm['delta_fr_mo']):>10} {_fmt(hm['delta_fr_mo']):>12}"
          f" {_fmt_pct(dm['ann_ret']):>10} {_fmt_pct(fm['ann_ret']):>9} {_fmt_pct(hm['ann_ret']):>11}")

print("=" * 110)

# ─────────────────────────────────────────────────────────────────────────────
# TABLE 4.5.3 — Buffer flows by regime
# ─────────────────────────────────────────────────────────────────────────────
print()
print("=" * 85)
print("Table 4.5.3 -- Buffer Flows by VSTOXX Regime  (run_042, T=85 months)")
print("=" * 85)
hdr = (f"{'Regime':<12} {'VSTOXX':>8} {'n':>4}"
       f" {'DRL fill':>10} {'FR fill':>8} {'Hoev fill':>10}"
       f" {'DRL dist':>10} {'FR dist':>8} {'Hoev dist':>10}")
print(hdr)
print("-" * 85)
for label, band, mask in regimes:
    n   = int(mask.sum())
    dbm = buffer_metrics(drl["f_tilde"], drl["d_tilde"], mask)
    fbm = buffer_metrics(fxd["f_tilde"], fxd["d_tilde"], mask)
    hbm = buffer_metrics(hoev_f_tilde, hoev_d_tilde, mask)
    print(f"{label:<12} {band:>8} {n:>4}"
          f" {dbm['fill_mean']:>10.5f} {fbm['fill_mean']:>8.5f} {hbm['fill_mean']:>10.5f}"
          f" {dbm['dist_mean']:>10.5f} {fbm['dist_mean']:>8.5f} {hbm['dist_mean']:>10.5f}")
print("=" * 85)

# ─────────────────────────────────────────────────────────────────────────────
# LaTeX
# ─────────────────────────────────────────────────────────────────────────────
print()
print("% -- LaTeX Table 4.5.2 -- FR Outcomes by Regime (3-way comparison) --")
print(r"\begin{table}[htbp]")
print(r"  \centering")
print(r"  \caption{FR Outcomes by VSTOXX Volatility Regime (out-of-sample, 2018--2025).}")
print(r"  \label{tab:regime_fr}")
print(r"  \begin{tabular}{lrrrrrrr}")
print(r"    \toprule")
print(r"    Regime & $n$ & \multicolumn{3}{c}{$\Delta\mathrm{FR}/\mathrm{mo}$} & \multicolumn{3}{c}{Annualised $\Delta\mathrm{FR}$} \\")
print(r"    \cmidrule(lr){3-5} \cmidrule(lr){6-8}")
print(r"    & & DRL & Fixed-Rule & Hoevenaars & DRL & Fixed-Rule & Hoevenaars \\")
print(r"    \midrule")
for label, band, mask in regimes:
    n  = int(mask.sum())
    dm = fr_metrics(drl["FR"], mask)
    fm = fr_metrics(fxd["FR"], mask)
    hm = fr_metrics(hoev_FR, mask)
    def _ann(v):
        return f"{v*100:+.1f}\\%" if not np.isnan(v) else "--"
    sep = r"    \midrule" if label == "Overall" else ""
    if sep:
        print(sep)
    print(f"    {label} & {n} & {dm['delta_fr_mo']:+.4f} & {fm['delta_fr_mo']:+.4f} & {hm['delta_fr_mo']:+.4f}"
          f" & {_ann(dm['ann_ret'])} & {_ann(fm['ann_ret'])} & {_ann(hm['ann_ret'])} \\\\")
print(r"    \bottomrule")
print(r"  \end{tabular}")
print(r"  \begin{tablenotes}\footnotesize")
print(r"  \item \textit{Notes:} $\Delta\mathrm{FR}/\mathrm{mo}$ is the mean of the true")
print(r"  month-over-month funding-ratio change within each VSTOXX regime,")
print(r"  computed as $\Delta\mathrm{FR}_t = \mathrm{FR}_t - \mathrm{FR}_{t-1}$ and")
print(r"  averaged over regime months. Annualised $\Delta\mathrm{FR} = \Delta\mathrm{FR}/\mathrm{mo} \times 12$.")
print(r"  Hoevenaars ALM uses the Bayesian-optimised v4 parameters from")
print(r"  Table~\ref{tab:hoevenaars_params}, evaluated on the identical historical path.")
print(r"  \end{tablenotes}")
print(r"\end{table}")

print()
print("% -- LaTeX Table 4.5.3 -- Buffer Flows by Regime (3-way comparison) --")
print(r"\begin{table}[htbp]")
print(r"  \centering")
print(r"  \caption{Buffer Flows by VSTOXX Volatility Regime (out-of-sample, 2018--2025).}")
print(r"  \label{tab:regime_buffer}")
print(r"  \begin{tabular}{lrrrrrrr}")
print(r"    \toprule")
print(r"    Regime & $n$ & \multicolumn{3}{c}{Mean Fill $\tilde{f}_t$} & \multicolumn{3}{c}{Mean Distribution $\tilde{d}_t$} \\")
print(r"    \cmidrule(lr){3-5} \cmidrule(lr){6-8}")
print(r"    & & DRL & Fixed-Rule & Hoevenaars & DRL & Fixed-Rule & Hoevenaars \\")
print(r"    \midrule")
for label, band, mask in regimes:
    n   = int(mask.sum())
    dbm = buffer_metrics(drl["f_tilde"], drl["d_tilde"], mask)
    fbm = buffer_metrics(fxd["f_tilde"], fxd["d_tilde"], mask)
    hbm = buffer_metrics(hoev_f_tilde, hoev_d_tilde, mask)
    sep = r"    \midrule" if label == "Overall" else ""
    if sep:
        print(sep)
    print(f"    {label} & {n} & {dbm['fill_mean']:.5f} & {fbm['fill_mean']:.5f} & {hbm['fill_mean']:.5f}"
          f" & {dbm['dist_mean']:.5f} & {fbm['dist_mean']:.5f} & {hbm['dist_mean']:.5f} \\\\")
print(r"    \bottomrule")
print(r"  \end{tabular}")
print(r"  \begin{tablenotes}\footnotesize")
print(r"  \item \textit{Notes:} Mean monthly fill $\tilde{f}_t$ and distribution $\tilde{d}_t$")
print(r"  as a fraction of total pension assets, conditional on VSTOXX regime.")
print(r"  All three agents subject to identical Art.\ 10d annual fill cap and FR$\geq$1.00")
print(r"  distribution constraint.")
print(r"  \end{tablenotes}")
print(r"\end{table}")
